# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    input_sync: true
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
